stages:
  - test
  - deploy

test:
  image: node:11-stretch-slim
  stage: test
  before_script:
    - npm ci
  script:
  - npm run test

deploy:
  image: node:11-stretch-slim
  stage: deploy
  variables:
    NODE_ENV: production
  before_script:
    - apt-get update -y && apt-get install openssh-client git g++ build-essential python -y
    - eval $(ssh-agent -s)
    - echo "$DEPLOYMENT_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - npm ci
  script:
  - npx shipit production deploy
  only:
  - master
